# Generated by Django 4.1.2 on 2022-10-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='buses',
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
    ]
