# Generated by Django 4.1.2 on 2022-10-10 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_stations_alter_buses_destination_alter_buses_origin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buses',
            new_name='Bus',
        ),
        migrations.RenameModel(
            old_name='Stations',
            new_name='Station',
        ),
    ]
