# Generated by Django 4.1.2 on 2022-10-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='buses',
            field=models.ManyToManyField(blank=True, related_name='passengers', to='buses.bus'),
        ),
    ]
